### ISSUE TITLE
The `Update staging k8 specs` goal can fail if it runs before the image link event from the previous goal has been ingested

### ISSUE THREAD

**Issue by whostolebenfrog** [atomist/atomist-internal-sdm#24]
There is nothing to control this at the moment - it's just a timing thing. Possibly the goal performance improvements are making this more likely to occur too.

The ideal fix for this is that there is an intermediary goal that is fulfilled by the `ImageLinked` system event firing. This ensures that the flow is as intended.

**Comment by slimslenderslacks** [comment]
timing issue on ImageLink possibly
